/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MiyaokaEmbedTweet {
        "src": string;
    }
    interface MiyaokaImgLoader {
        "delay": number;
        "duration": number;
        "opacity": number;
        "rotate": number;
        "scale": number;
        "src": string;
    }
}
declare global {
    interface HTMLMiyaokaEmbedTweetElement extends Components.MiyaokaEmbedTweet, HTMLStencilElement {
    }
    var HTMLMiyaokaEmbedTweetElement: {
        prototype: HTMLMiyaokaEmbedTweetElement;
        new (): HTMLMiyaokaEmbedTweetElement;
    };
    interface HTMLMiyaokaImgLoaderElement extends Components.MiyaokaImgLoader, HTMLStencilElement {
    }
    var HTMLMiyaokaImgLoaderElement: {
        prototype: HTMLMiyaokaImgLoaderElement;
        new (): HTMLMiyaokaImgLoaderElement;
    };
    interface HTMLElementTagNameMap {
        "miyaoka-embed-tweet": HTMLMiyaokaEmbedTweetElement;
        "miyaoka-img-loader": HTMLMiyaokaImgLoaderElement;
    }
}
declare namespace LocalJSX {
    interface MiyaokaEmbedTweet {
        "src"?: string;
    }
    interface MiyaokaImgLoader {
        "delay"?: number;
        "duration"?: number;
        "opacity"?: number;
        "rotate"?: number;
        "scale"?: number;
        "src"?: string;
    }
    interface IntrinsicElements {
        "miyaoka-embed-tweet": MiyaokaEmbedTweet;
        "miyaoka-img-loader": MiyaokaImgLoader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "miyaoka-embed-tweet": LocalJSX.MiyaokaEmbedTweet & JSXBase.HTMLAttributes<HTMLMiyaokaEmbedTweetElement>;
            "miyaoka-img-loader": LocalJSX.MiyaokaImgLoader & JSXBase.HTMLAttributes<HTMLMiyaokaImgLoaderElement>;
        }
    }
}
